"""
vastu/data.py — Complete Vastu Shastra Reference Data
=====================================================
45 Devtas (Vastu Purusha Mandala), 32 Entrance Padas,
Metal Strip Remedies, Color Therapy, Room Placement rules.
All data bilingual: English + Hindi.
"""

# ============================================================
# DIRECTIONS — compass mapping
# ============================================================
DIRECTIONS = {
    "N":  {"en": "North",     "hi": "उत्तर",      "degrees": (337.5, 22.5),  "element": "Water",  "element_hi": "जल",   "ruling_planet": "Mercury", "ruling_planet_hi": "बुध"},
    "NE": {"en": "Northeast", "hi": "ईशान",       "degrees": (22.5, 67.5),   "element": "Water",  "element_hi": "जल",   "ruling_planet": "Jupiter", "ruling_planet_hi": "गुरु"},
    "E":  {"en": "East",      "hi": "पूर्व",       "degrees": (67.5, 112.5),  "element": "Air",    "element_hi": "वायु", "ruling_planet": "Sun",     "ruling_planet_hi": "सूर्य"},
    "SE": {"en": "Southeast", "hi": "आग्नेय",     "degrees": (112.5, 157.5), "element": "Fire",   "element_hi": "अग्नि","ruling_planet": "Venus",   "ruling_planet_hi": "शुक्र"},
    "S":  {"en": "South",     "hi": "दक्षिण",      "degrees": (157.5, 202.5), "element": "Fire",   "element_hi": "अग्नि","ruling_planet": "Mars",    "ruling_planet_hi": "मंगल"},
    "SW": {"en": "Southwest", "hi": "नैऋत्य",     "degrees": (202.5, 247.5), "element": "Earth",  "element_hi": "पृथ्वी","ruling_planet": "Rahu",    "ruling_planet_hi": "राहु"},
    "W":  {"en": "West",      "hi": "पश्चिम",      "degrees": (247.5, 292.5), "element": "Air",    "element_hi": "वायु", "ruling_planet": "Saturn",  "ruling_planet_hi": "शनि"},
    "NW": {"en": "Northwest", "hi": "वायव्य",     "degrees": (292.5, 337.5), "element": "Air",    "element_hi": "वायु", "ruling_planet": "Moon",    "ruling_planet_hi": "चन्द्र"},
}

# ============================================================
# 45 DEVTAS — Vastu Purusha Mandala
# Each devta: name, hindi, zone, zone_hi, direction, element,
#             nature (+/-/neutral), energy_type, body_part,
#             activation_mantra, description (en/hi)
# ============================================================
DEVTAS_45 = [
    # ── ZONE 1: CENTRAL (Brahma Sthana) — 9 Devtas ──
    {
        "id": 1, "name": "Brahma", "name_hi": "ब्रह्मा",
        "zone": "Central", "zone_hi": "ब्रह्म स्थान",
        "direction": "Center", "direction_hi": "केंद्र",
        "element": "Ether", "element_hi": "आकाश",
        "nature": "supreme", "energy_type": "creative",
        "body_part": "Navel", "body_part_hi": "नाभि",
        "mantra": "Om Brahmane Namah",
        "desc_en": "Creator deity occupying the central zone. Governs creation, cosmic order, and spiritual consciousness. This zone must remain open and unobstructed.",
        "desc_hi": "केंद्रीय क्षेत्र के अधिष्ठाता देवता। सृष्टि, ब्रह्मांडीय व्यवस्था और आध्यात्मिक चेतना का शासन करते हैं। यह क्षेत्र खुला और अबाधित रहना चाहिए।",
        "grid_positions": [(3,3),(3,4),(3,5),(4,3),(4,4),(4,5),(5,3),(5,4),(5,5)],
    },
    {
        "id": 2, "name": "Aryama", "name_hi": "अर्यमा",
        "zone": "Central", "zone_hi": "ब्रह्म स्थान",
        "direction": "Center-South", "direction_hi": "केंद्र-दक्षिण",
        "element": "Ether", "element_hi": "आकाश",
        "nature": "positive", "energy_type": "ancestral",
        "body_part": "Chest", "body_part_hi": "छाती",
        "mantra": "Om Aryamne Namah",
        "desc_en": "Deity of ancestors and social bonds. Governs family harmony, inheritance, and ancestral blessings. Strengthen for family unity.",
        "desc_hi": "पितृ और सामाजिक बंधनों के देवता। पारिवारिक सद्भाव, विरासत और पैतृक आशीर्वाद का शासन करते हैं।",
        "grid_positions": [(5,3)],
    },
    {
        "id": 3, "name": "Vivasvan", "name_hi": "विवस्वान",
        "zone": "Central", "zone_hi": "ब्रह्म स्थान",
        "direction": "Center-East", "direction_hi": "केंद्र-पूर्व",
        "element": "Fire", "element_hi": "अग्नि",
        "nature": "positive", "energy_type": "solar",
        "body_part": "Eyes", "body_part_hi": "नेत्र",
        "mantra": "Om Vivasvate Namah",
        "desc_en": "Sun deity — source of life energy and vitality. Governs health, authority, and government relations. Morning sunlight must enter this zone.",
        "desc_hi": "सूर्य देवता — जीवन ऊर्जा और जीवनशक्ति का स्रोत। स्वास्थ्य, अधिकार और सरकारी संबंधों का शासन करते हैं।",
        "grid_positions": [(3,5)],
    },
    {
        "id": 4, "name": "Mitra", "name_hi": "मित्र",
        "zone": "Central", "zone_hi": "ब्रह्म स्थान",
        "direction": "Center-North", "direction_hi": "केंद्र-उत्तर",
        "element": "Water", "element_hi": "जल",
        "nature": "positive", "energy_type": "harmonious",
        "body_part": "Lungs", "body_part_hi": "फेफड़े",
        "mantra": "Om Mitraya Namah",
        "desc_en": "Deity of friendship, partnerships, and contracts. Governs all business alliances and social connections. Strengthens cooperative ventures.",
        "desc_hi": "मित्रता, साझेदारी और अनुबंधों के देवता। सभी व्यावसायिक गठबंधन और सामाजिक संबंधों का शासन करते हैं।",
        "grid_positions": [(3,3)],
    },
    {
        "id": 5, "name": "Mahidhara", "name_hi": "महीधर",
        "zone": "Central", "zone_hi": "ब्रह्म स्थान",
        "direction": "Center-West", "direction_hi": "केंद्र-पश्चिम",
        "element": "Earth", "element_hi": "पृथ्वी",
        "nature": "positive", "energy_type": "foundational",
        "body_part": "Spine", "body_part_hi": "रीढ़",
        "mantra": "Om Mahidharaya Namah",
        "desc_en": "Earth-bearer deity — foundation and stability. Governs structural integrity, foundation strength, and material security of the building.",
        "desc_hi": "पृथ्वी-धारक देवता — नींव और स्थिरता। भवन की संरचनात्मक अखंडता, नींव की मजबूती और भौतिक सुरक्षा का शासन करते हैं।",
        "grid_positions": [(5,5)],
    },
    {
        "id": 6, "name": "Savita", "name_hi": "सविता",
        "zone": "Central", "zone_hi": "ब्रह्म स्थान",
        "direction": "Center", "direction_hi": "केंद्र",
        "element": "Fire", "element_hi": "अग्नि",
        "nature": "positive", "energy_type": "creative",
        "body_part": "Heart", "body_part_hi": "हृदय",
        "mantra": "Om Savitre Namah",
        "desc_en": "Deity of creative inspiration and divine impulse. Governs artistic expression, innovation, and new beginnings in the household.",
        "desc_hi": "सृजनात्मक प्रेरणा और दिव्य प्रेरणा के देवता। कलात्मक अभिव्यक्ति, नवाचार और घर में नई शुरुआत का शासन करते हैं।",
        "grid_positions": [(4,4)],
    },
    {
        "id": 7, "name": "Jaya", "name_hi": "जय",
        "zone": "Central", "zone_hi": "ब्रह्म स्थान",
        "direction": "Center-NE", "direction_hi": "केंद्र-ईशान",
        "element": "Ether", "element_hi": "आकाश",
        "nature": "positive", "energy_type": "victorious",
        "body_part": "Arms", "body_part_hi": "भुजाएं",
        "mantra": "Om Jayaya Namah",
        "desc_en": "Deity of victory and triumph. Governs success in endeavors, competition, and overcoming obstacles. Activates winning energy.",
        "desc_hi": "विजय और सफलता के देवता। प्रयासों, प्रतिस्पर्धा और बाधाओं पर विजय प्राप्त करने का शासन करते हैं।",
        "grid_positions": [(3,4)],
    },
    {
        "id": 8, "name": "Indra", "name_hi": "इन्द्र",
        "zone": "Central", "zone_hi": "ब्रह्म स्थान",
        "direction": "Center-E", "direction_hi": "केंद्र-पूर्व",
        "element": "Air", "element_hi": "वायु",
        "nature": "positive", "energy_type": "authoritative",
        "body_part": "Right Hand", "body_part_hi": "दाहिना हाथ",
        "mantra": "Om Indraya Namah",
        "desc_en": "King of Devas — supreme authority and power. Governs leadership, governance, rain, and prosperity. The east-central zone channels his energy.",
        "desc_hi": "देवताओं के राजा — सर्वोच्च अधिकार और शक्ति। नेतृत्व, शासन, वर्षा और समृद्धि का शासन करते हैं।",
        "grid_positions": [(4,5)],
    },
    {
        "id": 9, "name": "Rudra", "name_hi": "रुद्र",
        "zone": "Central", "zone_hi": "ब्रह्म स्थान",
        "direction": "Center-NW", "direction_hi": "केंद्र-वायव्य",
        "element": "Air", "element_hi": "वायु",
        "nature": "fierce", "energy_type": "transformative",
        "body_part": "Throat", "body_part_hi": "कंठ",
        "mantra": "Om Rudraya Namah",
        "desc_en": "Fierce form of Shiva — transformation and destruction of negativity. Governs removal of obstacles, purification, and fierce protection.",
        "desc_hi": "शिव का उग्र रूप — नकारात्मकता का परिवर्तन और विनाश। बाधाओं को दूर करने, शुद्धिकरण और उग्र रक्षा का शासन करते हैं।",
        "grid_positions": [(4,3)],
    },

    # ── ZONE 2: NORTHEAST (Ishanya) — 4 Devtas ──
    {
        "id": 10, "name": "Shikhi", "name_hi": "शिखी",
        "zone": "Northeast", "zone_hi": "ईशान",
        "direction": "NE", "direction_hi": "ईशान",
        "element": "Water", "element_hi": "जल",
        "nature": "positive", "energy_type": "spiritual_fire",
        "body_part": "Head-Crown", "body_part_hi": "मस्तक-शिखर",
        "mantra": "Om Shikhine Namah",
        "desc_en": "Fire of spiritual awakening in the northeast. Governs spiritual ignition, meditation energy, and divine consciousness activation.",
        "desc_hi": "ईशान कोण में आध्यात्मिक जागरण की अग्नि। आध्यात्मिक प्रज्वलन, ध्यान ऊर्जा और दिव्य चेतना सक्रियण का शासन करती है।",
        "grid_positions": [(0,7)],
    },
    {
        "id": 11, "name": "Parjanya", "name_hi": "पर्जन्य",
        "zone": "Northeast", "zone_hi": "ईशान",
        "direction": "NE", "direction_hi": "ईशान",
        "element": "Water", "element_hi": "जल",
        "nature": "positive", "energy_type": "nourishing",
        "body_part": "Brain", "body_part_hi": "मस्तिष्क",
        "mantra": "Om Parjanyaya Namah",
        "desc_en": "Rain deity — nourishment and sustenance. Governs fertility, agricultural prosperity, and the flow of divine grace into the household.",
        "desc_hi": "वर्षा देवता — पोषण और जीविका। उर्वरता, कृषि समृद्धि और घर में दिव्य कृपा के प्रवाह का शासन करते हैं।",
        "grid_positions": [(1,7)],
    },
    {
        "id": 12, "name": "Jayant", "name_hi": "जयन्त",
        "zone": "Northeast", "zone_hi": "ईशान",
        "direction": "NE", "direction_hi": "ईशान",
        "element": "Water", "element_hi": "जल",
        "nature": "positive", "energy_type": "victorious",
        "body_part": "Forehead", "body_part_hi": "ललाट",
        "mantra": "Om Jayantaya Namah",
        "desc_en": "Son of Indra — victory and achievement. Governs competitive success, examination results, and triumph over rivals.",
        "desc_hi": "इन्द्रपुत्र — विजय और उपलब्धि। प्रतिस्पर्धात्मक सफलता, परीक्षा परिणाम और प्रतिद्वंद्वियों पर विजय का शासन करते हैं।",
        "grid_positions": [(0,6)],
    },
    {
        "id": 13, "name": "Aditi", "name_hi": "अदिति",
        "zone": "Northeast", "zone_hi": "ईशान",
        "direction": "NE", "direction_hi": "ईशान",
        "element": "Water", "element_hi": "जल",
        "nature": "supreme", "energy_type": "cosmic_mother",
        "body_part": "Third Eye", "body_part_hi": "तीसरा नेत्र",
        "mantra": "Om Aditye Namah",
        "desc_en": "Cosmic Mother — boundless, infinite consciousness. The supreme entrance pada. Governs unlimited prosperity, divine protection, and highest spiritual attainment.",
        "desc_hi": "ब्रह्मांडीय माता — असीम, अनंत चेतना। सर्वोच्च प्रवेश पद। असीमित समृद्धि, दिव्य सुरक्षा और उच्चतम आध्यात्मिक प्राप्ति का शासन करती हैं।",
        "grid_positions": [(1,6)],
    },

    # ── ZONE 3: EAST (Purva) — 4 Devtas ──
    {
        "id": 14, "name": "Aditya", "name_hi": "आदित्य",
        "zone": "East", "zone_hi": "पूर्व",
        "direction": "E", "direction_hi": "पूर्व",
        "element": "Air", "element_hi": "वायु",
        "nature": "positive", "energy_type": "authoritative",
        "body_part": "Right Arm", "body_part_hi": "दाहिनी भुजा",
        "mantra": "Om Adityaya Namah",
        "desc_en": "Solar Indra — Dikpala (guardian) of the East. Governs power, authority, government connections, and social status. East-facing main door activates Aditya's blessings.",
        "desc_hi": "सौर इन्द्र — पूर्व दिशा के दिक्पाल (संरक्षक)। शक्ति, अधिकार, सरकारी संबंध और सामाजिक प्रतिष्ठा का शासन करते हैं।",
        "grid_positions": [(3,8)],
    },
    {
        "id": 15, "name": "Surya", "name_hi": "सूर्य",
        "zone": "East", "zone_hi": "पूर्व",
        "direction": "E", "direction_hi": "पूर्व",
        "element": "Fire", "element_hi": "अग्नि",
        "nature": "positive", "energy_type": "solar",
        "body_part": "Eyes", "body_part_hi": "नेत्र",
        "mantra": "Om Suryaya Namah",
        "desc_en": "Solar deity — primary source of prana. Governs health, fame, leadership, and father's well-being. Morning sunlight from east is essential.",
        "desc_hi": "सूर्य देवता — प्राण का प्राथमिक स्रोत। स्वास्थ्य, यश, नेतृत्व और पिता की भलाई का शासन करते हैं।",
        "grid_positions": [(2,8)],
    },
    {
        "id": 16, "name": "Satya", "name_hi": "सत्य",
        "zone": "East", "zone_hi": "पूर्व",
        "direction": "E", "direction_hi": "पूर्व",
        "element": "Ether", "element_hi": "आकाश",
        "nature": "positive", "energy_type": "truthful",
        "body_part": "Tongue", "body_part_hi": "जिह्वा",
        "mantra": "Om Satyaya Namah",
        "desc_en": "Deity of truth and righteousness. Governs honesty in dealings, legal matters, and dharmic conduct of household members.",
        "desc_hi": "सत्य और धार्मिकता के देवता। व्यापार में ईमानदारी, कानूनी मामले और घर के सदस्यों के धार्मिक आचरण का शासन करते हैं।",
        "grid_positions": [(4,8)],
    },
    {
        "id": 17, "name": "Bhrisha", "name_hi": "भृश",
        "zone": "East", "zone_hi": "पूर्व",
        "direction": "E", "direction_hi": "पूर्व",
        "element": "Fire", "element_hi": "अग्नि",
        "nature": "positive", "energy_type": "forceful",
        "body_part": "Right Shoulder", "body_part_hi": "दाहिना कंधा",
        "mantra": "Om Bhrishaya Namah",
        "desc_en": "Deity of force and intensity. Governs courage, physical strength, and martial energy. Activates warrior spirit and determination.",
        "desc_hi": "बल और तीव्रता के देवता। साहस, शारीरिक शक्ति और योद्धा ऊर्जा का शासन करते हैं।",
        "grid_positions": [(5,8)],
    },

    # ── ZONE 4: SOUTHEAST (Agneya) — 4 Devtas ──
    {
        "id": 18, "name": "Agni", "name_hi": "अग्नि",
        "zone": "Southeast", "zone_hi": "आग्नेय",
        "direction": "SE", "direction_hi": "आग्नेय",
        "element": "Fire", "element_hi": "अग्नि",
        "nature": "positive", "energy_type": "transformative_fire",
        "body_part": "Right Knee", "body_part_hi": "दाहिना घुटना",
        "mantra": "Om Agnaye Namah",
        "desc_en": "Fire deity — lord of the Southeast. Governs cooking, digestion, transformation, and purification. Kitchen placement here is ideal.",
        "desc_hi": "अग्नि देवता — आग्नेय कोण के स्वामी। पाक-शाला, पाचन, परिवर्तन और शुद्धिकरण का शासन करते हैं। रसोई यहाँ रखना आदर्श है।",
        "grid_positions": [(7,7)],
    },
    {
        "id": 19, "name": "Pushan", "name_hi": "पूषन",
        "zone": "Southeast", "zone_hi": "आग्नेय",
        "direction": "SE", "direction_hi": "आग्नेय",
        "element": "Fire", "element_hi": "अग्नि",
        "nature": "positive", "energy_type": "nourishing",
        "body_part": "Right Calf", "body_part_hi": "दाहिनी पिंडली",
        "mantra": "Om Pushne Namah",
        "desc_en": "Deity of nourishment and journeys. Governs safe travel, food abundance, livestock, and prosperity through movement.",
        "desc_hi": "पोषण और यात्रा के देवता। सुरक्षित यात्रा, भोजन की प्रचुरता, पशुधन और गतिशीलता से समृद्धि का शासन करते हैं।",
        "grid_positions": [(6,7)],
    },
    {
        "id": 20, "name": "Vitatha", "name_hi": "वितथ",
        "zone": "Southeast", "zone_hi": "आग्नेय",
        "direction": "SE", "direction_hi": "आग्नेय",
        "element": "Fire", "element_hi": "अग्नि",
        "nature": "negative", "energy_type": "deceptive",
        "body_part": "Right Thigh", "body_part_hi": "दाहिनी जाँघ",
        "mantra": "Om Vitathaya Namah",
        "desc_en": "Deity of falsehood and illusion. This negative energy must be neutralized. Avoid important documents, safes, or valuables in this zone.",
        "desc_hi": "असत्य और माया के देवता। इस नकारात्मक ऊर्जा को निष्प्रभावित करना आवश्यक है। इस क्षेत्र में महत्वपूर्ण दस्तावेज़ या कीमती सामान न रखें।",
        "grid_positions": [(7,6)],
    },
    {
        "id": 21, "name": "Grihakshata", "name_hi": "गृहक्षत",
        "zone": "Southeast", "zone_hi": "आग्नेय",
        "direction": "SE", "direction_hi": "आग्नेय",
        "element": "Fire", "element_hi": "अग्नि",
        "nature": "negative", "energy_type": "conflicting",
        "body_part": "Right Ankle", "body_part_hi": "दाहिना टखना",
        "mantra": "Om Grihakshataya Namah",
        "desc_en": "Deity of household conflicts and destruction. Causes domestic quarrels and property damage when activated. Must be kept calm with remedies.",
        "desc_hi": "घरेलू विवाद और विनाश के देवता। सक्रिय होने पर घरेलू झगड़े और संपत्ति क्षति का कारण बनते हैं। उपायों से शांत रखना चाहिए।",
        "grid_positions": [(6,6)],
    },

    # ── ZONE 5: SOUTH (Dakshina) — 4 Devtas ──
    {
        "id": 22, "name": "Yama", "name_hi": "यम",
        "zone": "South", "zone_hi": "दक्षिण",
        "direction": "S", "direction_hi": "दक्षिण",
        "element": "Fire", "element_hi": "अग्नि",
        "nature": "fierce", "energy_type": "disciplinary",
        "body_part": "Right Foot", "body_part_hi": "दाहिना पैर",
        "mantra": "Om Yamaya Namah",
        "desc_en": "Lord of Death and Dharma — ruler of the South. Governs discipline, law, justice, and karmic consequences. Heavy structures here provide stability.",
        "desc_hi": "मृत्यु और धर्म के देवता — दक्षिण के शासक। अनुशासन, कानून, न्याय और कर्म-फल का शासन करते हैं। यहाँ भारी संरचनाएँ स्थिरता देती हैं।",
        "grid_positions": [(8,4)],
    },
    {
        "id": 23, "name": "Gandharva", "name_hi": "गंधर्व",
        "zone": "South", "zone_hi": "दक्षिण",
        "direction": "S", "direction_hi": "दक्षिण",
        "element": "Air", "element_hi": "वायु",
        "nature": "positive", "energy_type": "artistic",
        "body_part": "Left Foot", "body_part_hi": "बायाँ पैर",
        "mantra": "Om Gandharvaya Namah",
        "desc_en": "Celestial musician — arts and beauty. Governs music, dance, fine arts, and aesthetic sensibility. Rare positive energy in the southern zone.",
        "desc_hi": "दिव्य संगीतकार — कला और सौंदर्य। संगीत, नृत्य, ललित कला और सौंदर्य संवेदनशीलता का शासन करते हैं। दक्षिण क्षेत्र में दुर्लभ सकारात्मक ऊर्जा।",
        "grid_positions": [(8,3)],
    },
    {
        "id": 24, "name": "Bhringaraja", "name_hi": "भृंगराज",
        "zone": "South", "zone_hi": "दक्षिण",
        "direction": "S", "direction_hi": "दक्षिण",
        "element": "Fire", "element_hi": "अग्नि",
        "nature": "negative", "energy_type": "disease",
        "body_part": "Lower Spine", "body_part_hi": "कमर निचला हिस्सा",
        "mantra": "Om Bhringarajaya Namah",
        "desc_en": "Deity associated with disease and suffering. This negative energy causes health problems. Avoid bedrooms and sitting areas in this zone.",
        "desc_hi": "रोग और पीड़ा से संबंधित देवता। यह नकारात्मक ऊर्जा स्वास्थ्य समस्याएँ उत्पन्न करती है। इस क्षेत्र में शयनकक्ष और बैठने की जगह न रखें।",
        "grid_positions": [(8,5)],
    },
    {
        "id": 25, "name": "Mriga", "name_hi": "मृग",
        "zone": "South", "zone_hi": "दक्षिण",
        "direction": "S", "direction_hi": "दक्षिण",
        "element": "Earth", "element_hi": "पृथ्वी",
        "nature": "neutral", "energy_type": "movement",
        "body_part": "Legs", "body_part_hi": "टाँगें",
        "mantra": "Om Mrigaya Namah",
        "desc_en": "Deer deity — movement, instinct, and wandering. Governs travel, migration, and restlessness. Neutral energy suitable for corridors and passages.",
        "desc_hi": "मृग देवता — गति, सहज ज्ञान और भ्रमण। यात्रा, प्रवास और अस्थिरता का शासन करते हैं। गलियारों और मार्गों के लिए उपयुक्त तटस्थ ऊर्जा।",
        "grid_positions": [(7,5)],
    },

    # ── ZONE 6: SOUTHWEST (Nairutya) — 4 Devtas ──
    {
        "id": 26, "name": "Nairuti", "name_hi": "नैऋति",
        "zone": "Southwest", "zone_hi": "नैऋत्य",
        "direction": "SW", "direction_hi": "नैऋत्य",
        "element": "Earth", "element_hi": "पृथ्वी",
        "nature": "negative", "energy_type": "demonic",
        "body_part": "Left Knee", "body_part_hi": "बायाँ घुटना",
        "mantra": "Om Nairutaye Namah",
        "desc_en": "Demon deity of the Southwest — lord of Rakshasas. Governs obstacles, destruction, and negativity. Must be weighed down with heavy objects and master bedroom.",
        "desc_hi": "नैऋत्य के राक्षस देवता — राक्षसों के स्वामी। बाधाओं, विनाश और नकारात्मकता का शासन करते हैं। भारी वस्तुओं और मुख्य शयनकक्ष से दबाना चाहिए।",
        "grid_positions": [(7,0)],
    },
    {
        "id": 27, "name": "Dauvarika", "name_hi": "दौवारिक",
        "zone": "Southwest", "zone_hi": "नैऋत्य",
        "direction": "SW", "direction_hi": "नैऋत्य",
        "element": "Earth", "element_hi": "पृथ्वी",
        "nature": "neutral", "energy_type": "guarding",
        "body_part": "Left Calf", "body_part_hi": "बाईं पिंडली",
        "mantra": "Om Dauvarikaya Namah",
        "desc_en": "Gatekeeper deity — guards the entrance to negative zones. Provides protection when properly activated. Place security features here.",
        "desc_hi": "द्वारपाल देवता — नकारात्मक क्षेत्रों के प्रवेश द्वार की रक्षा करते हैं। उचित सक्रियण पर सुरक्षा प्रदान करते हैं।",
        "grid_positions": [(6,0)],
    },
    {
        "id": 28, "name": "Shosha", "name_hi": "शोष",
        "zone": "Southwest", "zone_hi": "नैऋत्य",
        "direction": "SW", "direction_hi": "नैऋत्य",
        "element": "Earth", "element_hi": "पृथ्वी",
        "nature": "negative", "energy_type": "depleting",
        "body_part": "Left Thigh", "body_part_hi": "बाईं जाँघ",
        "mantra": "Om Shoshaya Namah",
        "desc_en": "Deity of depletion and drying. Causes financial losses, energy drain, and vitality reduction. Must be suppressed with heavy furniture.",
        "desc_hi": "क्षय और सूखापन के देवता। वित्तीय हानि, ऊर्जा की कमी और जीवनशक्ति में कमी का कारण बनते हैं। भारी फर्नीचर से दबाना चाहिए।",
        "grid_positions": [(7,1)],
    },
    {
        "id": 29, "name": "Papayakshma", "name_hi": "पापयक्ष्मा",
        "zone": "Southwest", "zone_hi": "नैऋत्य",
        "direction": "SW", "direction_hi": "नैऋत्य",
        "element": "Earth", "element_hi": "पृथ्वी",
        "nature": "negative", "energy_type": "suffering",
        "body_part": "Left Ankle", "body_part_hi": "बायाँ टखना",
        "mantra": "Om Papayakshmaya Namah",
        "desc_en": "Deity of sin and tuberculosis (ancient disease). Most negative energy — causes chronic illness and suffering. Never place water elements here.",
        "desc_hi": "पाप और क्षय रोग के देवता। सबसे नकारात्मक ऊर्जा — दीर्घकालिक बीमारी और पीड़ा का कारण। यहाँ कभी जल तत्व न रखें।",
        "grid_positions": [(6,1)],
    },

    # ── ZONE 7: WEST (Paschima) — 4 Devtas ──
    {
        "id": 30, "name": "Varuna", "name_hi": "वरुण",
        "zone": "West", "zone_hi": "पश्चिम",
        "direction": "W", "direction_hi": "पश्चिम",
        "element": "Water", "element_hi": "जल",
        "nature": "positive", "energy_type": "oceanic",
        "body_part": "Left Arm", "body_part_hi": "बाईं भुजा",
        "mantra": "Om Varunaya Namah",
        "desc_en": "Lord of oceans and cosmic order. Governs water bodies, rain, emotional balance, and cosmic justice. Ideal for water features and tanks.",
        "desc_hi": "समुद्रों और ब्रह्मांडीय व्यवस्था के देवता। जल स्रोत, वर्षा, भावनात्मक संतुलन और ब्रह्मांडीय न्याय का शासन करते हैं।",
        "grid_positions": [(4,0)],
    },
    {
        "id": 31, "name": "Asura", "name_hi": "असुर",
        "zone": "West", "zone_hi": "पश्चिम",
        "direction": "W", "direction_hi": "पश्चिम",
        "element": "Air", "element_hi": "वायु",
        "nature": "negative", "energy_type": "oppositional",
        "body_part": "Left Shoulder", "body_part_hi": "बायाँ कंधा",
        "mantra": "Om Asuraya Namah",
        "desc_en": "Demon deity — opposition and conflict. Causes legal disputes, enemy attacks, and power struggles. Needs heavy suppression and protective remedies.",
        "desc_hi": "राक्षस देवता — विरोध और संघर्ष। कानूनी विवाद, शत्रु आक्रमण और सत्ता संघर्ष का कारण बनते हैं। भारी दमन और सुरक्षात्मक उपायों की आवश्यकता।",
        "grid_positions": [(5,0)],
    },
    {
        "id": 32, "name": "Roga", "name_hi": "रोग",
        "zone": "West", "zone_hi": "पश्चिम",
        "direction": "W", "direction_hi": "पश्चिम",
        "element": "Air", "element_hi": "वायु",
        "nature": "negative", "energy_type": "disease",
        "body_part": "Left Hand", "body_part_hi": "बायाँ हाथ",
        "mantra": "Om Rogaya Namah",
        "desc_en": "Disease deity — illness and physical affliction. Causes chronic health problems when active. Avoid sleeping or sitting in this zone.",
        "desc_hi": "रोग देवता — बीमारी और शारीरिक कष्ट। सक्रिय होने पर दीर्घकालिक स्वास्थ्य समस्याएँ उत्पन्न करते हैं। इस क्षेत्र में सोना या बैठना टालें।",
        "grid_positions": [(3,0)],
    },
    {
        "id": 33, "name": "Naga", "name_hi": "नाग",
        "zone": "West", "zone_hi": "पश्चिम",
        "direction": "W", "direction_hi": "पश्चिम",
        "element": "Earth", "element_hi": "पृथ्वी",
        "nature": "neutral", "energy_type": "hidden_wealth",
        "body_part": "Abdomen", "body_part_hi": "उदर",
        "mantra": "Om Nagaya Namah",
        "desc_en": "Serpent deity — hidden treasures and underground wealth. Governs mineral resources, hidden knowledge, and kundalini energy.",
        "desc_hi": "सर्प देवता — छिपे खजाने और भूमिगत संपदा। खनिज संसाधनों, गुप्त ज्ञान और कुंडलिनी ऊर्जा का शासन करते हैं।",
        "grid_positions": [(2,0)],
    },

    # ── ZONE 8: NORTHWEST (Vayavya) — 4 Devtas ──
    {
        "id": 34, "name": "Vayu", "name_hi": "वायु",
        "zone": "Northwest", "zone_hi": "वायव्य",
        "direction": "NW", "direction_hi": "वायव्य",
        "element": "Air", "element_hi": "वायु",
        "nature": "positive", "energy_type": "movement",
        "body_part": "Left Hand-Upper", "body_part_hi": "बायाँ ऊपरी हाथ",
        "mantra": "Om Vayave Namah",
        "desc_en": "Wind deity — lord of the Northwest. Governs air circulation, change, movement, and social connections. Guest rooms and storage ideal here.",
        "desc_hi": "वायु देवता — वायव्य के स्वामी। वायु संचार, परिवर्तन, गति और सामाजिक संबंधों का शासन करते हैं। अतिथि कक्ष और भंडारण यहाँ आदर्श है।",
        "grid_positions": [(0,0)],
    },
    {
        "id": 35, "name": "Mukhya", "name_hi": "मुख्य",
        "zone": "Northwest", "zone_hi": "वायव्य",
        "direction": "NW", "direction_hi": "वायव्य",
        "element": "Air", "element_hi": "वायु",
        "nature": "positive", "energy_type": "identity",
        "body_part": "Face", "body_part_hi": "मुख",
        "mantra": "Om Mukhyaya Namah",
        "desc_en": "Deity of identity and social face. Governs reputation, public image, self-expression, and social standing in the community.",
        "desc_hi": "पहचान और सामाजिक छवि के देवता। प्रतिष्ठा, सार्वजनिक छवि, आत्म-अभिव्यक्ति और सामुदायिक सामाजिक स्थिति का शासन करते हैं।",
        "grid_positions": [(1,0)],
    },
    {
        "id": 36, "name": "Bhallata", "name_hi": "भल्लाट",
        "zone": "Northwest", "zone_hi": "वायव्य",
        "direction": "NW", "direction_hi": "वायव्य",
        "element": "Air", "element_hi": "वायु",
        "nature": "positive", "energy_type": "strength",
        "body_part": "Left Upper Arm", "body_part_hi": "बाईं ऊपरी भुजा",
        "mantra": "Om Bhallataya Namah",
        "desc_en": "Deity of physical strength and endurance. Governs physical fitness, sports achievements, and raw physical power.",
        "desc_hi": "शारीरिक शक्ति और सहनशीलता के देवता। शारीरिक फिटनेस, खेल उपलब्धियों और कच्ची शारीरिक शक्ति का शासन करते हैं।",
        "grid_positions": [(0,1)],
    },
    {
        "id": 37, "name": "Soma", "name_hi": "सोम",
        "zone": "Northwest", "zone_hi": "वायव्य",
        "direction": "NW", "direction_hi": "वायव्य",
        "element": "Water", "element_hi": "जल",
        "nature": "positive", "energy_type": "mental",
        "body_part": "Mind", "body_part_hi": "मन",
        "mantra": "Om Somaya Namah",
        "desc_en": "Moon deity — mind, emotions, and psychic abilities. Governs mental peace, intuition, maternal bond, and emotional intelligence.",
        "desc_hi": "चन्द्र देवता — मन, भावनाएँ और मानसिक क्षमताएँ। मानसिक शांति, अंतर्ज्ञान, मातृ बंधन और भावनात्मक बुद्धि का शासन करते हैं।",
        "grid_positions": [(1,1)],
    },

    # ── ZONE 9: NORTH (Uttara) — 4 Devtas ──
    {
        "id": 38, "name": "Kubera", "name_hi": "कुबेर",
        "zone": "North", "zone_hi": "उत्तर",
        "direction": "N", "direction_hi": "उत्तर",
        "element": "Water", "element_hi": "जल",
        "nature": "supreme", "energy_type": "wealth",
        "body_part": "Head-Left", "body_part_hi": "बायाँ मस्तक",
        "mantra": "Om Kuberaya Namah",
        "desc_en": "Lord of Wealth — treasurer of the gods. Governs financial prosperity, material abundance, and treasure accumulation. Keep cash box and locker facing North.",
        "desc_hi": "धन के देवता — देवताओं के कोषाध्यक्ष। वित्तीय समृद्धि, भौतिक प्रचुरता और खजाना संचय का शासन करते हैं। तिजोरी उत्तर की ओर रखें।",
        "grid_positions": [(0,4)],
    },
    {
        "id": 39, "name": "Isha", "name_hi": "ईश",
        "zone": "North", "zone_hi": "उत्तर",
        "direction": "N", "direction_hi": "उत्तर",
        "element": "Water", "element_hi": "जल",
        "nature": "supreme", "energy_type": "divine",
        "body_part": "Head-Top", "body_part_hi": "शिखर",
        "mantra": "Om Ishaya Namah",
        "desc_en": "Shiva energy — the supreme lord. Governs spiritual liberation, meditation, and highest consciousness. The most sacred direction after Northeast.",
        "desc_hi": "शिव ऊर्जा — परम ईश्वर। आध्यात्मिक मुक्ति, ध्यान और उच्चतम चेतना का शासन करते हैं। ईशान के बाद सबसे पवित्र दिशा।",
        "grid_positions": [(0,5)],
    },
    {
        "id": 40, "name": "Diti", "name_hi": "दिति",
        "zone": "North", "zone_hi": "उत्तर",
        "direction": "N", "direction_hi": "उत्तर",
        "element": "Earth", "element_hi": "पृथ्वी",
        "nature": "neutral", "energy_type": "material",
        "body_part": "Head-Right", "body_part_hi": "दाहिना मस्तक",
        "mantra": "Om Ditaye Namah",
        "desc_en": "Mother of demons — material desires and earthly bonds. Neutral energy that governs worldly attachments and material pursuits. Balance with spiritual practice.",
        "desc_hi": "दैत्यों की माता — भौतिक इच्छाएँ और सांसारिक बंधन। तटस्थ ऊर्जा जो सांसारिक आसक्ति और भौतिक खोज का शासन करती है।",
        "grid_positions": [(0,3)],
    },
    {
        "id": 41, "name": "Bhudhar", "name_hi": "भूधर",
        "zone": "North", "zone_hi": "उत्तर",
        "direction": "N", "direction_hi": "उत्तर",
        "element": "Water", "element_hi": "जल",
        "nature": "supreme", "energy_type": "wealth_foundation",
        "body_part": "Crown", "body_part_hi": "मुकुट",
        "mantra": "Om Bhudharaya Namah",
        "desc_en": "Earth-upholder on the North wall — material foundation and wealth accumulation. Per Manasara, guards the northern treasure zone alongside Kubera.",
        "desc_hi": "उत्तरी दीवार पर पृथ्वी-धारक — भौतिक आधार और धन संचय। मानसार के अनुसार, कुबेर के साथ उत्तरी खजाना क्षेत्र की रक्षा करते हैं।",
        "grid_positions": [(0,2)],
    },

    # ── ZONE 10: SPECIAL/TRANSITIONAL — 4 Devtas ──
    {
        "id": 42, "name": "Apah", "name_hi": "आपः",
        "zone": "Special", "zone_hi": "विशेष",
        "direction": "W-NW", "direction_hi": "पश्चिम-वायव्य",
        "element": "Water", "element_hi": "जल",
        "nature": "positive", "energy_type": "purifying",
        "body_part": "Kidneys", "body_part_hi": "गुर्दे",
        "mantra": "Om Apahe Namah",
        "desc_en": "Water element deity — purification and cleansing. Governs water supply, drainage, and bodily fluid balance. Ideal for bathrooms and water storage.",
        "desc_hi": "जल तत्व देवता — शुद्धिकरण और सफाई। जल आपूर्ति, जल निकासी और शारीरिक द्रव संतुलन का शासन करते हैं।",
        "grid_positions": [(2,1)],
    },
    {
        "id": 43, "name": "Savitra", "name_hi": "सवित्र",
        "zone": "Special", "zone_hi": "विशेष",
        "direction": "E-NE", "direction_hi": "पूर्व-ईशान",
        "element": "Fire", "element_hi": "अग्नि",
        "nature": "positive", "energy_type": "inspirational",
        "body_part": "Solar Plexus", "body_part_hi": "सौर जाल",
        "mantra": "Om Savitre Namah",
        "desc_en": "Solar creative deity — divine inspiration and new beginnings. Governs early morning energy, sunrise rituals, and creative impulse activation.",
        "desc_hi": "सौर सृजनात्मक देवता — दिव्य प्रेरणा और नई शुरुआत। प्रातःकालीन ऊर्जा, सूर्योदय अनुष्ठान और सृजनात्मक आवेग सक्रियण का शासन करते हैं।",
        "grid_positions": [(2,7)],
    },
    {
        "id": 44, "name": "Apavatsa", "name_hi": "अपवत्स",
        "zone": "Special", "zone_hi": "विशेष",
        "direction": "S-SE", "direction_hi": "दक्षिण-आग्नेय",
        "element": "Fire", "element_hi": "अग्नि",
        "nature": "negative", "energy_type": "childlessness",
        "body_part": "Reproductive", "body_part_hi": "प्रजनन",
        "mantra": "Om Apavatsaya Namah",
        "desc_en": "Deity of childlessness and reproductive obstacles. Negative energy affecting progeny and fertility. Requires specific remedies for couples seeking children.",
        "desc_hi": "संतानहीनता और प्रजनन बाधाओं के देवता। संतति और उर्वरता को प्रभावित करने वाली नकारात्मक ऊर्जा। संतान चाहने वाले दम्पतियों के लिए विशेष उपायों की आवश्यकता।",
        "grid_positions": [(7,4)],
    },
    {
        "id": 45, "name": "Aryaka", "name_hi": "अर्यक",
        "zone": "Special", "zone_hi": "विशेष",
        "direction": "S-SW", "direction_hi": "दक्षिण-नैऋत्य",
        "element": "Earth", "element_hi": "पृथ्वी",
        "nature": "neutral", "energy_type": "ancestral",
        "body_part": "Bones", "body_part_hi": "हड्डियाँ",
        "mantra": "Om Aryakaya Namah",
        "desc_en": "Ancestral deity — connection to lineage and hereditary traits. Governs family legacy, genetic health, and ancestral karma resolution.",
        "desc_hi": "पैतृक देवता — वंश और आनुवंशिक लक्षणों से संबंध। पारिवारिक विरासत, आनुवंशिक स्वास्थ्य और पैतृक कर्म समाधान का शासन करते हैं।",
        "grid_positions": [(7,3)],
    },
]

# ============================================================
# 32 ENTRANCE PADAS — 8 per direction
# Each: pada_number, name, name_hi, direction, quality, quality_hi,
#       quality_score (1-5, 5=best), effects_en, effects_hi,
#       suitable_for, avoid_for, devta_ruling
# ============================================================
ENTRANCE_PADAS = [
    # ── NORTH (N1-N8) — Generally auspicious ──
    {"pada": "N1", "name": "Mukhya",   "name_hi": "मुख्य",     "direction": "N", "quality": "GOOD",      "quality_hi": "शुभ",       "score": 4, "devta": "Mukhya",   "effects_en": "Good for career growth and professional success. Brings steady income and reputation.",                   "effects_hi": "करियर वृद्धि और व्यावसायिक सफलता के लिए शुभ। स्थिर आय और प्रतिष्ठा लाता है।",            "suitable": ["residential", "office"],       "avoid": []},
    {"pada": "N2", "name": "Bhallata", "name_hi": "भल्लाट",    "direction": "N", "quality": "GOOD",      "quality_hi": "शुभ",       "score": 4, "devta": "Bhallata", "effects_en": "Brings physical strength, stamina, and good health to occupants. Suitable for sports persons.",            "effects_hi": "निवासियों को शारीरिक शक्ति, सहनशक्ति और अच्छा स्वास्थ्य प्रदान करता है।",                  "suitable": ["residential", "gym"],          "avoid": []},
    {"pada": "N3", "name": "Soma",     "name_hi": "सोम",       "direction": "N", "quality": "GOOD",      "quality_hi": "शुभ",       "score": 4, "devta": "Soma",     "effects_en": "Enhances mental peace, emotional intelligence, and psychic abilities. Good for meditation centers.",        "effects_hi": "मानसिक शांति, भावनात्मक बुद्धि और मानसिक क्षमताओं को बढ़ाता है।",                            "suitable": ["residential", "meditation"],   "avoid": []},
    {"pada": "N4", "name": "Diti",     "name_hi": "दिति",      "direction": "N", "quality": "EXCELLENT", "quality_hi": "सर्वश्रेष्ठ", "score": 5, "devta": "Diti",   "effects_en": "Supreme wealth entrance — brings material abundance, business prosperity, and financial growth.",            "effects_hi": "सर्वश्रेष्ठ धन प्रवेश — भौतिक प्रचुरता, व्यापार समृद्धि और वित्तीय वृद्धि लाता है।",      "suitable": ["all"],                         "avoid": []},
    {"pada": "N5", "name": "Aditi",    "name_hi": "अदिति",     "direction": "N", "quality": "SUPREME",   "quality_hi": "परम शुभ",    "score": 5, "devta": "Aditi",   "effects_en": "The SUPREME entrance — Aditi pada. Best for all purposes. Brings unlimited prosperity, divine protection, and spiritual growth.", "effects_hi": "सर्वोच्च प्रवेश — अदिति पद। सभी उद्देश्यों के लिए सर्वश्रेष्ठ। असीमित समृद्धि, दिव्य सुरक्षा और आध्यात्मिक विकास।", "suitable": ["all"], "avoid": []},
    {"pada": "N6", "name": "Kubera",   "name_hi": "कुबेर",     "direction": "N", "quality": "EXCELLENT", "quality_hi": "सर्वश्रेष्ठ", "score": 5, "devta": "Kubera", "effects_en": "Kubera's direct blessing — wealth accumulation, treasury, and financial security. Keep this zone pristine.",  "effects_hi": "कुबेर का प्रत्यक्ष आशीर्वाद — धन संचय, कोषागार और वित्तीय सुरक्षा।",                      "suitable": ["all"],                         "avoid": []},
    {"pada": "N7", "name": "Isha",     "name_hi": "ईश",        "direction": "N", "quality": "GOOD",      "quality_hi": "शुभ",       "score": 4, "devta": "Isha",     "effects_en": "Shiva energy entrance — spiritual growth, meditation support, and divine consciousness expansion.",          "effects_hi": "शिव ऊर्जा प्रवेश — आध्यात्मिक विकास, ध्यान सहायता और दिव्य चेतना विस्तार।",              "suitable": ["residential", "temple"],       "avoid": ["commercial"]},
    {"pada": "N8", "name": "Parjanya", "name_hi": "पर्जन्य",   "direction": "N", "quality": "NEUTRAL",   "quality_hi": "सामान्य",   "score": 3, "devta": "Parjanya", "effects_en": "Mixed results — can bring delays but eventual success. Nourishment comes slowly but sustainably.",           "effects_hi": "मिश्रित परिणाम — देरी हो सकती है पर अंततः सफलता। पोषण धीरे लेकिन टिकाऊ होता है।",         "suitable": ["residential"],                 "avoid": ["business"]},

    # ── EAST (E1-E8) — Second best direction ──
    {"pada": "E1", "name": "Shikhi",   "name_hi": "शिखी",     "direction": "E", "quality": "GOOD",      "quality_hi": "शुभ",       "score": 4, "devta": "Shikhi",   "effects_en": "Spiritual fire entrance — ignites ambition, spiritual growth, and intellectual pursuits.",                   "effects_hi": "आध्यात्मिक अग्नि प्रवेश — महत्वाकांक्षा, आध्यात्मिक वृद्धि और बौद्धिक खोज को प्रज्वलित करता है।", "suitable": ["residential", "school"],  "avoid": []},
    {"pada": "E2", "name": "Jayant",   "name_hi": "जयन्त",    "direction": "E", "quality": "EXCELLENT", "quality_hi": "सर्वश्रेष्ठ", "score": 5, "devta": "Jayant", "effects_en": "Victory entrance — guarantees success in competitions, exams, legal battles, and business ventures.",         "effects_hi": "विजय प्रवेश — प्रतियोगिताओं, परीक्षाओं, कानूनी लड़ाइयों और व्यावसायिक उद्यमों में सफलता की गारंटी।", "suitable": ["all"], "avoid": []},
    {"pada": "E3", "name": "Aditya",   "name_hi": "आदित्य",    "direction": "E", "quality": "EXCELLENT", "quality_hi": "सर्वश्रेष्ठ", "score": 5, "devta": "Aditya", "effects_en": "Royal entrance — brings authority, government favor, political power, and social dominance.",                "effects_hi": "राजसी प्रवेश — अधिकार, सरकारी कृपा, राजनीतिक शक्ति और सामाजिक प्रभुत्व लाता है।",         "suitable": ["all"],                         "avoid": []},
    {"pada": "E4", "name": "Surya",    "name_hi": "सूर्य",     "direction": "E", "quality": "EXCELLENT", "quality_hi": "सर्वश्रेष्ठ", "score": 5, "devta": "Surya",  "effects_en": "Solar entrance — health, vitality, fame, and leadership qualities. Morning sun directly enters the home.",   "effects_hi": "सौर प्रवेश — स्वास्थ्य, जीवनशक्ति, यश और नेतृत्व गुण। प्रातः सूर्य सीधे घर में प्रवेश करता है।", "suitable": ["all"], "avoid": []},
    {"pada": "E5", "name": "Satya",    "name_hi": "सत्य",      "direction": "E", "quality": "GOOD",      "quality_hi": "शुभ",       "score": 4, "devta": "Satya",    "effects_en": "Truth entrance — honesty in dealings, legal protection, and righteous living. Good for law offices.",        "effects_hi": "सत्य प्रवेश — व्यापार में ईमानदारी, कानूनी सुरक्षा और धार्मिक जीवन।",                      "suitable": ["residential", "office"],       "avoid": []},
    {"pada": "E6", "name": "Bhrisha",  "name_hi": "भृश",       "direction": "E", "quality": "NEUTRAL",   "quality_hi": "सामान्य",   "score": 3, "devta": "Bhrisha",  "effects_en": "Forceful entrance — can bring aggression and intensity. Suitable for military, sports, but not peaceful homes.", "effects_hi": "बलशाली प्रवेश — आक्रामकता और तीव्रता ला सकता है। सैन्य, खेल के लिए उपयुक्त।",           "suitable": ["gym", "military"],             "avoid": ["residential"]},
    {"pada": "E7", "name": "Akasha",   "name_hi": "आकाश",      "direction": "E", "quality": "CHALLENGE", "quality_hi": "चुनौतीपूर्ण", "score": 2, "devta": "Akasha", "effects_en": "Void entrance — emptiness, confusion, and lack of direction. May cause financial instability.",               "effects_hi": "शून्य प्रवेश — खालीपन, भ्रम और दिशाहीनता। वित्तीय अस्थिरता का कारण बन सकता है।",          "suitable": [],                              "avoid": ["all"]},
    {"pada": "E8", "name": "Anil",     "name_hi": "अनिल",      "direction": "E", "quality": "CHALLENGE", "quality_hi": "चुनौतीपूर्ण", "score": 2, "devta": "Anil",   "effects_en": "Restless wind entrance — instability, frequent changes, and inability to settle. Avoid for permanent residence.", "effects_hi": "अस्थिर वायु प्रवेश — अस्थिरता, बार-बार बदलाव और स्थिर न हो पाना।",                     "suitable": [],                              "avoid": ["residential"]},

    # ── SOUTH (S1-S8) — Mostly challenging ──
    {"pada": "S1", "name": "Vitatha",     "name_hi": "वितथ",     "direction": "S", "quality": "CHALLENGE", "quality_hi": "अशुभ",    "score": 1, "devta": "Vitatha",     "effects_en": "Falsehood entrance — deception, fraud, and financial losses through betrayal. Strictly avoid.",                 "effects_hi": "असत्य प्रवेश — धोखा, छल और विश्वासघात से वित्तीय हानि। सख्ती से बचें।",                    "suitable": [],    "avoid": ["all"]},
    {"pada": "S2", "name": "Grihakshata", "name_hi": "गृहक्षत",  "direction": "S", "quality": "CHALLENGE", "quality_hi": "अशुभ",    "score": 1, "devta": "Grihakshata", "effects_en": "Domestic destruction — causes family quarrels, divorce, property disputes, and constant tension at home.",       "effects_hi": "घरेलू विनाश — पारिवारिक झगड़े, तलाक, संपत्ति विवाद और लगातार तनाव का कारण।",                "suitable": [],    "avoid": ["all"]},
    {"pada": "S3", "name": "Yama",        "name_hi": "यम",       "direction": "S", "quality": "CHALLENGE", "quality_hi": "अशुभ",    "score": 1, "devta": "Yama",        "effects_en": "Death entrance — severe health problems, accidents, and premature death energy. Most dangerous pada.",         "effects_hi": "मृत्यु प्रवेश — गंभीर स्वास्थ्य समस्याएँ, दुर्घटनाएँ और अकाल मृत्यु ऊर्जा। सबसे खतरनाक पद।", "suitable": [], "avoid": ["all"]},
    {"pada": "S4", "name": "Gandharva",   "name_hi": "गंधर्व",   "direction": "S", "quality": "GOOD",      "quality_hi": "शुभ",     "score": 4, "devta": "Gandharva",   "effects_en": "Rare positive South entrance — excellent for artists, musicians, dancers. Brings creative prosperity.",         "effects_hi": "दुर्लभ सकारात्मक दक्षिण प्रवेश — कलाकारों, संगीतकारों, नर्तकों के लिए उत्कृष्ट। सृजनात्मक समृद्धि।", "suitable": ["art_studio", "music_school"], "avoid": []},
    {"pada": "S5", "name": "Bhringaraja", "name_hi": "भृंगराज",  "direction": "S", "quality": "CHALLENGE", "quality_hi": "अशुभ",    "score": 1, "devta": "Bhringaraja", "effects_en": "Disease entrance — chronic illness, hospital visits, and persistent health deterioration.",                     "effects_hi": "रोग प्रवेश — दीर्घकालिक बीमारी, अस्पताल यात्राएँ और लगातार स्वास्थ्य गिरावट।",             "suitable": [],    "avoid": ["all"]},
    {"pada": "S6", "name": "Mriga",       "name_hi": "मृग",      "direction": "S", "quality": "NEUTRAL",   "quality_hi": "सामान्य", "score": 3, "devta": "Mriga",       "effects_en": "Animal energy entrance — restlessness and wandering. Occupants may travel excessively or relocate frequently.", "effects_hi": "पशु ऊर्जा प्रवेश — अस्थिरता और भटकाव। निवासी अत्यधिक यात्रा या बार-बार स्थानांतरण कर सकते हैं।", "suitable": ["warehouse"], "avoid": ["residential"]},
    {"pada": "S7", "name": "Nairuti",     "name_hi": "नैऋति",    "direction": "S", "quality": "CHALLENGE", "quality_hi": "अशुभ",    "score": 1, "devta": "Nairuti",     "effects_en": "Demon entrance — attracts negative entities, theft, and sudden catastrophic losses.",                           "effects_hi": "राक्षस प्रवेश — नकारात्मक शक्तियों, चोरी और अचानक विनाशकारी हानि को आकर्षित करता है।",     "suitable": [],    "avoid": ["all"]},
    {"pada": "S8", "name": "Papayakshma", "name_hi": "पापयक्ष्मा","direction": "S", "quality": "CHALLENGE", "quality_hi": "अशुभ",   "score": 1, "devta": "Papayakshma", "effects_en": "Sin entrance — chronic suffering, karmic debt accumulation, and tuberculosis-like wasting diseases.",            "effects_hi": "पाप प्रवेश — दीर्घकालिक पीड़ा, कर्म ऋण संचय और क्षय रोग जैसी विनाशकारी बीमारियाँ।",       "suitable": [],    "avoid": ["all"]},

    # ── WEST (W1-W8) — Mixed results ──
    {"pada": "W1", "name": "Dauvarika",  "name_hi": "दौवारिक",   "direction": "W", "quality": "NEUTRAL",   "quality_hi": "सामान्य", "score": 3, "devta": "Dauvarika",  "effects_en": "Gatekeeper entrance — moderate protection but can restrict growth. Occupants feel guarded but limited.",         "effects_hi": "द्वारपाल प्रवेश — मध्यम सुरक्षा लेकिन विकास को सीमित कर सकता है।",                         "suitable": ["warehouse"],                    "avoid": ["business"]},
    {"pada": "W2", "name": "Shosha",     "name_hi": "शोष",       "direction": "W", "quality": "CHALLENGE", "quality_hi": "अशुभ",    "score": 1, "devta": "Shosha",     "effects_en": "Depletion entrance — financial drain, energy exhaustion, and gradual decay of prosperity.",                       "effects_hi": "क्षय प्रवेश — वित्तीय पतन, ऊर्जा थकान और समृद्धि का क्रमिक क्षय।",                         "suitable": [],                               "avoid": ["all"]},
    {"pada": "W3", "name": "Nairuti-W",  "name_hi": "नैऋति-प",   "direction": "W", "quality": "CHALLENGE", "quality_hi": "अशुभ",    "score": 1, "devta": "Nairuti",    "effects_en": "Demon gate west — obstacles, court cases, and enemy attacks from western direction.",                              "effects_hi": "पश्चिम राक्षस द्वार — बाधाएँ, अदालती मामले और पश्चिम दिशा से शत्रु आक्रमण।",              "suitable": [],                               "avoid": ["all"]},
    {"pada": "W4", "name": "Varuna",     "name_hi": "वरुण",      "direction": "W", "quality": "EXCELLENT", "quality_hi": "सर्वश्रेष्ठ", "score": 5, "devta": "Varuna", "effects_en": "Ocean lord entrance — brings emotional balance, cosmic justice, and water-related prosperity.",                    "effects_hi": "सागर स्वामी प्रवेश — भावनात्मक संतुलन, ब्रह्मांडीय न्याय और जल-संबंधी समृद्धि।",           "suitable": ["all"],                          "avoid": []},
    {"pada": "W5", "name": "Asura",      "name_hi": "असुर",      "direction": "W", "quality": "CHALLENGE", "quality_hi": "अशुभ",    "score": 1, "devta": "Asura",      "effects_en": "Opposition entrance — constant rivals, legal fights, and workplace politics. Highly inauspicious.",               "effects_hi": "विरोध प्रवेश — लगातार प्रतिद्वंद्वी, कानूनी लड़ाइयाँ और कार्यस्थल राजनीति।",              "suitable": [],                               "avoid": ["all"]},
    {"pada": "W6", "name": "Roga",       "name_hi": "रोग",       "direction": "W", "quality": "CHALLENGE", "quality_hi": "अशुभ",    "score": 1, "devta": "Roga",       "effects_en": "Disease entrance west — chronic health issues, especially respiratory and joint problems.",                        "effects_hi": "पश्चिम रोग प्रवेश — दीर्घकालिक स्वास्थ्य समस्याएँ, विशेषकर श्वसन और जोड़ों की समस्याएँ।", "suitable": [],                               "avoid": ["all"]},
    {"pada": "W7", "name": "Naga",       "name_hi": "नाग",       "direction": "W", "quality": "GOOD",      "quality_hi": "शुभ",     "score": 4, "devta": "Naga",       "effects_en": "Serpent treasure entrance — hidden wealth, underground resources, and unexpected financial gains.",                 "effects_hi": "सर्प खजाना प्रवेश — छिपा धन, भूमिगत संसाधन और अप्रत्याशित वित्तीय लाभ।",                 "suitable": ["residential", "mining"],        "avoid": []},
    {"pada": "W8", "name": "Pushpadant", "name_hi": "पुष्पदंत",  "direction": "W", "quality": "EXCELLENT", "quality_hi": "सर्वश्रेष्ठ", "score": 5, "devta": "Pushpadant","effects_en": "Wealth flower entrance — one of the best West padas. Brings abundance, luxury, and consistent prosperity.",     "effects_hi": "धन पुष्प प्रवेश — सर्वश्रेष्ठ पश्चिम पदों में से एक। प्रचुरता, विलासिता और निरंतर समृद्धि।", "suitable": ["all"],                       "avoid": []},
]

# ============================================================
# METAL STRIP REMEDIES — direction → metal mapping
# ============================================================
METAL_REMEDIES = {
    "N":  {"metal": "Copper",      "metal_hi": "ताँबा",     "purpose_en": "Energy activation and channel clearing in the North",          "purpose_hi": "उत्तर में ऊर्जा सक्रियण और चैनल सफाई",          "placement": "Bury 3-foot copper strip along the northern wall foundation",    "placement_hi": "उत्तरी दीवार की नींव के साथ 3 फीट ताँबे की पट्टी दबाएँ"},
    "NE": {"metal": "Brass",       "metal_hi": "पीतल",      "purpose_en": "Wealth activation and spiritual energy amplification",         "purpose_hi": "धन सक्रियण और आध्यात्मिक ऊर्जा प्रवर्धन",       "placement": "Place brass strip at NE corner, buried 6 inches deep",            "placement_hi": "ईशान कोने पर पीतल की पट्टी 6 इंच गहरी दबाएँ"},
    "E":  {"metal": "Copper",      "metal_hi": "ताँबा",     "purpose_en": "Solar energy reception and authority enhancement",              "purpose_hi": "सौर ऊर्जा ग्रहण और अधिकार वृद्धि",              "placement": "Install copper strip along the eastern wall at 3 feet height",    "placement_hi": "पूर्वी दीवार पर 3 फीट ऊँचाई पर ताँबे की पट्टी लगाएँ"},
    "SE": {"metal": "Copper",      "metal_hi": "ताँबा",     "purpose_en": "Fire element regulation and cooking energy balance",            "purpose_hi": "अग्नि तत्व नियंत्रण और रसोई ऊर्जा संतुलन",     "placement": "Place copper strip near the kitchen entrance, SE corner",         "placement_hi": "रसोई प्रवेश द्वार के पास, आग्नेय कोने पर ताँबे की पट्टी रखें"},
    "S":  {"metal": "Iron",        "metal_hi": "लोहा",      "purpose_en": "Protection from Yama's energy and disease prevention",          "purpose_hi": "यम ऊर्जा से सुरक्षा और रोग निवारण",             "placement": "Bury iron strip along the southern boundary wall",                 "placement_hi": "दक्षिणी सीमा दीवार के साथ लोहे की पट्टी दबाएँ"},
    "SW": {"metal": "Zinc",        "metal_hi": "जस्ता",     "purpose_en": "Stability enhancement and negative energy suppression",         "purpose_hi": "स्थिरता वृद्धि और नकारात्मक ऊर्जा दमन",         "placement": "Place zinc strip under the SW corner foundation stone",            "placement_hi": "नैऋत्य कोने की नींव के पत्थर के नीचे जस्ते की पट्टी रखें"},
    "W":  {"metal": "Silver",      "metal_hi": "चाँदी",     "purpose_en": "Emotional balance and Varuna energy harmonization",             "purpose_hi": "भावनात्मक संतुलन और वरुण ऊर्जा सामंजस्य",       "placement": "Install silver strip at the western wall, eye-level height",       "placement_hi": "पश्चिमी दीवार पर आँख की ऊँचाई पर चाँदी की पट्टी लगाएँ"},
    "NW": {"metal": "Aluminium",   "metal_hi": "एल्यूमिनियम","purpose_en": "Air element regulation and social energy flow",                "purpose_hi": "वायु तत्व नियंत्रण और सामाजिक ऊर्जा प्रवाह",   "placement": "Place aluminium strip near the NW window or ventilation",          "placement_hi": "वायव्य खिड़की या हवादान के पास एल्यूमिनियम की पट्टी रखें"},
    "Center": {"metal": "Gold-plated", "metal_hi": "सोने की परत","purpose_en": "Brahma activation and cosmic consciousness alignment",      "purpose_hi": "ब्रह्म सक्रियण और ब्रह्मांडीय चेतना संरेखण",    "placement": "Place gold-plated strip at the geometric center of the house",     "placement_hi": "घर के ज्यामितीय केंद्र पर सोने की परत वाली पट्टी रखें"},
}

# ============================================================
# COLOR THERAPY — direction → recommended colors
# ============================================================
COLOR_THERAPY = {
    "N":  {"colors": ["Blue", "Green"],           "colors_hi": ["नीला", "हरा"],          "element": "Water", "reasoning_en": "North is governed by Mercury and water element. Cool colors enhance concentration and wealth flow.",      "reasoning_hi": "उत्तर बुध और जल तत्व द्वारा शासित। ठंडे रंग एकाग्रता और धन प्रवाह बढ़ाते हैं।"},
    "NE": {"colors": ["White", "Cream", "Light Yellow"], "colors_hi": ["सफेद", "क्रीम", "हल्का पीला"], "element": "Water", "reasoning_en": "Northeast is the most sacred zone. Pure, light colors maintain spiritual sanctity.", "reasoning_hi": "ईशान सबसे पवित्र क्षेत्र है। शुद्ध, हल्के रंग आध्यात्मिक पवित्रता बनाए रखते हैं।"},
    "E":  {"colors": ["Green", "Light Brown"],    "colors_hi": ["हरा", "हल्का भूरा"],    "element": "Air",   "reasoning_en": "East brings solar energy. Green represents growth and brown grounds the solar intensity.",                   "reasoning_hi": "पूर्व सौर ऊर्जा लाता है। हरा विकास का प्रतिनिधित्व करता है और भूरा सौर तीव्रता को संतुलित करता है।"},
    "SE": {"colors": ["Orange", "Red", "Pink"],   "colors_hi": ["नारंगी", "लाल", "गुलाबी"],"element": "Fire", "reasoning_en": "Southeast is Agni's zone. Warm fire colors enhance cooking energy and digestive power.",                     "reasoning_hi": "आग्नेय अग्नि का क्षेत्र है। गर्म अग्नि रंग रसोई ऊर्जा और पाचन शक्ति बढ़ाते हैं।"},
    "S":  {"colors": ["Red", "Coral", "Maroon"],  "colors_hi": ["लाल", "मूंगा", "मैरून"],  "element": "Fire", "reasoning_en": "South is Yama's domain. Strong reds provide protection and grounding against death energy.",                 "reasoning_hi": "दक्षिण यम का क्षेत्र है। गहरे लाल रंग मृत्यु ऊर्जा से सुरक्षा और स्थिरता देते हैं।"},
    "SW": {"colors": ["Brown", "Earth Tones", "Beige"], "colors_hi": ["भूरा", "मिट्टी के रंग", "बेज"], "element": "Earth", "reasoning_en": "Southwest needs heavy, earthy colors for stability and to suppress negative Nairuti energy.", "reasoning_hi": "नैऋत्य को स्थिरता और नकारात्मक नैऋति ऊर्जा को दबाने के लिए भारी, मिट्टी के रंगों की आवश्यकता।"},
    "W":  {"colors": ["Blue", "Grey", "White"],   "colors_hi": ["नीला", "स्लेटी", "सफेद"],"element": "Air",  "reasoning_en": "West is Varuna's domain (water lord). Blue and grey connect with ocean energy and emotional balance.",       "reasoning_hi": "पश्चिम वरुण का क्षेत्र है। नीला और स्लेटी सागर ऊर्जा और भावनात्मक संतुलन से जोड़ते हैं।"},
    "NW": {"colors": ["Grey", "White", "Silver"], "colors_hi": ["स्लेटी", "सफेद", "रजत"],"element": "Air",  "reasoning_en": "Northwest is Vayu's zone. Neutral, airy colors promote movement, change, and guest comfort.",                "reasoning_hi": "वायव्य वायु का क्षेत्र है। तटस्थ, हल्के रंग गति, परिवर्तन और अतिथि आराम बढ़ाते हैं।"},
}

# ============================================================
# ROOM PLACEMENT — ideal locations per room type
# ============================================================
ROOM_PLACEMENT = {
    "pooja": {
        "name_en": "Pooja Room / Temple",        "name_hi": "पूजा कक्ष / मंदिर",
        "ideal":     ["NE", "E", "N"],           "ideal_hi": ["ईशान", "पूर्व", "उत्तर"],
        "acceptable": [],                         "acceptable_hi": [],
        "avoid":     ["S", "SW", "SE"],          "avoid_hi": ["दक्षिण", "नैऋत्य", "आग्नेय"],
        "reason_en": "Northeast is the zone of divine consciousness (Isha, Aditi). Prayer facing East/North aligns with solar and Kubera energy.",
        "reason_hi": "ईशान दिव्य चेतना का क्षेत्र है। पूर्व/उत्तर की ओर मुख करके प्रार्थना सौर और कुबेर ऊर्जा से जुड़ती है।",
        "tips_en": ["Face East or North while praying", "Keep idols away from wall — leave gap", "Use marble or light-colored flooring", "Never place below staircase or toilet"],
        "tips_hi": ["प्रार्थना करते समय पूर्व या उत्तर की ओर मुख करें", "मूर्तियों को दीवार से दूर रखें — अंतर छोड़ें", "संगमरमर या हल्के रंग का फर्श उपयोग करें", "कभी सीढ़ी या शौचालय के नीचे न रखें"],
    },
    "kitchen": {
        "name_en": "Kitchen",                     "name_hi": "रसोई",
        "ideal":     ["SE"],                      "ideal_hi": ["आग्नेय"],
        "acceptable": ["NW", "E"],                "acceptable_hi": ["वायव्य", "पूर्व"],
        "avoid":     ["NE", "N", "SW"],           "avoid_hi": ["ईशान", "उत्तर", "नैऋत्य"],
        "reason_en": "Southeast is Agni's (fire god) zone — natural alignment for cooking. Face East while cooking for health and prosperity.",
        "reason_hi": "आग्नेय अग्नि देवता का क्षेत्र है — रसोई के लिए प्राकृतिक संरेखण। स्वास्थ्य और समृद्धि के लिए पूर्व की ओर मुख करके पकाएँ।",
        "tips_en": ["Cook facing East", "Gas stove in SE corner", "Water source in NE corner of kitchen", "Never place kitchen under or above toilet"],
        "tips_hi": ["पूर्व की ओर मुख करके पकाएँ", "गैस चूल्हा आग्नेय कोने में", "रसोई के ईशान कोने में जल स्रोत", "रसोई कभी शौचालय के ऊपर/नीचे न रखें"],
    },
    "master_bedroom": {
        "name_en": "Master Bedroom",              "name_hi": "मुख्य शयनकक्ष",
        "ideal":     ["SW"],                      "ideal_hi": ["नैऋत्य"],
        "acceptable": ["S", "W"],                 "acceptable_hi": ["दक्षिण", "पश्चिम"],
        "avoid":     ["NE", "N", "E"],            "avoid_hi": ["ईशान", "उत्तर", "पूर्व"],
        "reason_en": "Southwest represents stability and authority. The head of household in SW commands respect and controls the house energy.",
        "reason_hi": "नैऋत्य स्थिरता और अधिकार का प्रतिनिधित्व करता है। नैऋत्य में गृहस्वामी सम्मान प्राप्त करता है और घर की ऊर्जा नियंत्रित करता है।",
        "tips_en": ["Head pointing South while sleeping", "Heavy furniture in SW corner", "No mirror facing the bed", "Avoid beam above the bed"],
        "tips_hi": ["सोते समय सिर दक्षिण की ओर", "नैऋत्य कोने में भारी फर्नीचर", "बिस्तर की ओर दर्पण न रखें", "बिस्तर के ऊपर बीम से बचें"],
    },
    "living_room": {
        "name_en": "Living Room / Drawing Room",  "name_hi": "बैठक / ड्राइंग रूम",
        "ideal":     ["NE", "N", "E"],            "ideal_hi": ["ईशान", "उत्तर", "पूर्व"],
        "acceptable": ["NW"],                     "acceptable_hi": ["वायव्य"],
        "avoid":     ["SW", "S"],                 "avoid_hi": ["नैऋत्य", "दक्षिण"],
        "reason_en": "Northeast and North zones receive maximum positive cosmic energy. Living room here ensures family harmony and auspicious gatherings.",
        "reason_hi": "ईशान और उत्तर क्षेत्र अधिकतम सकारात्मक ब्रह्मांडीय ऊर्जा प्राप्त करते हैं। यहाँ बैठक पारिवारिक सद्भाव सुनिश्चित करती है।",
        "tips_en": ["Furniture in South and West walls", "Keep NE corner open and clutter-free", "Main seating should face North or East", "Place TV in SE or NW"],
        "tips_hi": ["फर्नीचर दक्षिण और पश्चिम दीवारों पर", "ईशान कोना खुला और साफ रखें", "मुख्य बैठक उत्तर या पूर्व की ओर", "टीवी आग्नेय या वायव्य में"],
    },
    "bathroom": {
        "name_en": "Bathroom / Toilet",            "name_hi": "स्नानघर / शौचालय",
        "ideal":     ["NW"],                       "ideal_hi": ["वायव्य"],
        "acceptable": ["W", "S"],                  "acceptable_hi": ["पश्चिम", "दक्षिण"],
        "avoid":     ["NE", "SW", "E", "Center"],  "avoid_hi": ["ईशान", "नैऋत्य", "पूर्व", "केंद्र"],
        "reason_en": "Northwest (Vayu zone) ensures air circulation for hygiene. Never in Northeast (spiritual pollution) or center (Brahma disturbance).",
        "reason_hi": "वायव्य (वायु क्षेत्र) स्वच्छता के लिए वायु संचार सुनिश्चित करता है। ईशान (आध्यात्मिक प्रदूषण) या केंद्र (ब्रह्म विघ्न) में कभी नहीं।",
        "tips_en": ["Toilet seat facing North or South", "Door should not face kitchen or pooja room", "Keep exhaust fan active", "Use light colors inside"],
        "tips_hi": ["शौचालय सीट उत्तर या दक्षिण की ओर", "दरवाज़ा रसोई या पूजा कक्ष की ओर न हो", "एक्ज़ॉस्ट फैन चालू रखें", "अंदर हल्के रंग उपयोग करें"],
    },
    "staircase": {
        "name_en": "Staircase",                    "name_hi": "सीढ़ी",
        "ideal":     ["S", "W", "SW"],             "ideal_hi": ["दक्षिण", "पश्चिम", "नैऋत्य"],
        "acceptable": ["NW"],                      "acceptable_hi": ["वायव्य"],
        "avoid":     ["NE", "Center", "N", "E"],   "avoid_hi": ["ईशान", "केंद्र", "उत्तर", "पूर्व"],
        "reason_en": "Stairs should rise from North to South or East to West (clockwise). Heavy construction in SW suppresses negative Nairuti energy.",
        "reason_hi": "सीढ़ियाँ उत्तर से दक्षिण या पूर्व से पश्चिम (दक्षिणावर्त) चढ़नी चाहिए। नैऋत्य में भारी निर्माण नकारात्मक ऊर्जा को दबाता है।",
        "tips_en": ["Always clockwise rotation", "Odd number of steps", "Never in center of house", "Avoid spiral staircases"],
        "tips_hi": ["हमेशा दक्षिणावर्त घूर्णन", "विषम संख्या में सीढ़ियाँ", "घर के केंद्र में कभी नहीं", "सर्पिल सीढ़ियों से बचें"],
    },
    "water_tank_underground": {
        "name_en": "Underground Water Tank / Well", "name_hi": "भूमिगत पानी की टंकी / कुआँ",
        "ideal":     ["NE", "N", "E"],              "ideal_hi": ["ईशान", "उत्तर", "पूर्व"],
        "acceptable": [],                            "acceptable_hi": [],
        "avoid":     ["SW", "S", "SE", "Center"],    "avoid_hi": ["नैऋत्य", "दक्षिण", "आग्नेय", "केंद्र"],
        "reason_en": "Northeast is the water element zone. Underground water here activates Parjanya (rain) and Aditi (abundance) energy fields.",
        "reason_hi": "ईशान जल तत्व क्षेत्र है। यहाँ भूमिगत जल पर्जन्य (वर्षा) और अदिति (प्रचुरता) ऊर्जा क्षेत्रों को सक्रिय करता है।",
        "tips_en": ["Bore well in NE", "Keep NE corner lower than other corners", "Water flow towards NE", "Never store water in SW"],
        "tips_hi": ["बोरवेल ईशान में", "ईशान कोना अन्य कोनों से नीचा रखें", "जल प्रवाह ईशान की ओर", "नैऋत्य में कभी जल भंडारण न करें"],
    },
    "water_tank_overhead": {
        "name_en": "Overhead Water Tank",            "name_hi": "ऊपरी पानी की टंकी",
        "ideal":     ["SW", "W", "S"],               "ideal_hi": ["नैऋत्य", "पश्चिम", "दक्षिण"],
        "acceptable": ["NW"],                         "acceptable_hi": ["वायव्य"],
        "avoid":     ["NE", "N", "E", "Center"],      "avoid_hi": ["ईशान", "उत्तर", "पूर्व", "केंद्र"],
        "reason_en": "Overhead tanks add weight — SW needs heaviness. Placing heavy tank in NE blocks divine energy flow (opposite of underground water).",
        "reason_hi": "ऊपरी टंकी भार जोड़ती है — नैऋत्य को भारीपन चाहिए। ईशान में भारी टंकी दिव्य ऊर्जा प्रवाह को अवरुद्ध करती है।",
        "tips_en": ["SW corner of terrace", "Height should not exceed building parapet", "Keep NE of terrace open", "Metal tank preferred over plastic"],
        "tips_hi": ["छत के नैऋत्य कोने पर", "ऊँचाई भवन की मुंडेर से अधिक न हो", "छत का ईशान खुला रखें", "प्लास्टिक से धातु टंकी बेहतर"],
    },
    "study_room": {
        "name_en": "Study Room / Office",            "name_hi": "अध्ययन कक्ष / कार्यालय",
        "ideal":     ["NE", "N", "E", "NW"],         "ideal_hi": ["ईशान", "उत्तर", "पूर्व", "वायव्य"],
        "acceptable": ["W"],                          "acceptable_hi": ["पश्चिम"],
        "avoid":     ["S", "SW", "SE"],               "avoid_hi": ["दक्षिण", "नैऋत्य", "आग्नेय"],
        "reason_en": "Northeast receives Jupiter's and Aditi's wisdom energy. Face East or North while studying for maximum concentration and retention.",
        "reason_hi": "ईशान गुरु और अदिति की ज्ञान ऊर्जा प्राप्त करता है। अधिकतम एकाग्रता के लिए पूर्व या उत्तर की ओर मुख करके अध्ययन करें।",
        "tips_en": ["Desk facing East or North", "Bookshelf on South or West wall", "Avoid sitting under beam", "Natural light from East preferred"],
        "tips_hi": ["डेस्क पूर्व या उत्तर की ओर", "किताबों की अलमारी दक्षिण या पश्चिम दीवार पर", "बीम के नीचे बैठने से बचें", "पूर्व से प्राकृतिक प्रकाश बेहतर"],
    },
    "children_bedroom": {
        "name_en": "Children's Bedroom",              "name_hi": "बच्चों का शयनकक्ष",
        "ideal":     ["NW", "W"],                      "ideal_hi": ["वायव्य", "पश्चिम"],
        "acceptable": ["N"],                            "acceptable_hi": ["उत्तर"],
        "avoid":     ["SW", "SE", "S"],                 "avoid_hi": ["नैऋत्य", "आग्नेय", "दक्षिण"],
        "reason_en": "Northwest's air energy keeps children active and creative. SW is for the head of household only — children here become dominating.",
        "reason_hi": "वायव्य की वायु ऊर्जा बच्चों को सक्रिय और सृजनशील रखती है। नैऋत्य केवल गृहस्वामी के लिए — बच्चे यहाँ प्रभुत्वशाली बन जाते हैं।",
        "tips_en": ["Head pointing East while sleeping", "Study desk in NE corner of room", "Bright, cheerful colors", "Avoid dark themes"],
        "tips_hi": ["सोते समय सिर पूर्व की ओर", "कमरे के ईशान कोने में अध्ययन डेस्क", "चमकीले, खुशनुमा रंग", "गहरे विषयों से बचें"],
    },
}

# ============================================================
# BUILDING TYPES — grid type selection
# ============================================================
BUILDING_TYPES = {
    "residential":  {"grid": "manduka",      "grid_size": 8, "name_en": "Manduka Mandala (8x8)", "name_hi": "मंडूक मंडल (8x8)", "desc_en": "Standard residential grid — 64 squares for homes and apartments",        "desc_hi": "मानक आवासीय ग्रिड — घरों और अपार्टमेंट के लिए 64 वर्ग"},
    "commercial":   {"grid": "manduka",      "grid_size": 8, "name_en": "Manduka Mandala (8x8)", "name_hi": "मंडूक मंडल (8x8)", "desc_en": "Commercial grid — 64 squares for offices, shops, and factories",          "desc_hi": "व्यावसायिक ग्रिड — कार्यालयों, दुकानों और कारखानों के लिए 64 वर्ग"},
    "temple":       {"grid": "paramasayika", "grid_size": 9, "name_en": "Paramasayika Mandala (9x9)", "name_hi": "परमसायिक मंडल (9x9)", "desc_en": "Sacred grid — 81 squares for temples, ashrams, and spiritual centers", "desc_hi": "पवित्र ग्रिड — मंदिरों, आश्रमों और आध्यात्मिक केंद्रों के लिए 81 वर्ग"},
}

# ============================================================
# VASTU PURUSHA BODY MAPPING — body orientation in mandala
# ============================================================
VASTU_PURUSHA_BODY = {
    "head":      {"direction": "NE", "direction_hi": "ईशान",  "significance_en": "Spiritual consciousness — keep open, light, elevated", "significance_hi": "आध्यात्मिक चेतना — खुला, हल्का, ऊँचा रखें"},
    "face":      {"direction": "N",  "direction_hi": "उत्तर",  "significance_en": "Identity, reputation — Kubera's wealth zone",          "significance_hi": "पहचान, प्रतिष्ठा — कुबेर का धन क्षेत्र"},
    "chest":     {"direction": "E",  "direction_hi": "पूर्व",   "significance_en": "Vitality, solar prana — morning sunlight entry",       "significance_hi": "जीवनशक्ति, सौर प्राण — प्रातः सूर्य प्रकाश प्रवेश"},
    "navel":     {"direction": "Center", "direction_hi": "केंद्र", "significance_en": "Brahma sthana — cosmic center, must be open",     "significance_hi": "ब्रह्म स्थान — ब्रह्मांडीय केंद्र, खुला रहना चाहिए"},
    "right_arm": {"direction": "SE", "direction_hi": "आग्नेय", "significance_en": "Fire energy — cooking, transformation",                "significance_hi": "अग्नि ऊर्जा — पाक, परिवर्तन"},
    "left_arm":  {"direction": "NW", "direction_hi": "वायव्य", "significance_en": "Wind energy — movement, guests, storage",              "significance_hi": "वायु ऊर्जा — गति, अतिथि, भंडारण"},
    "right_leg": {"direction": "S",  "direction_hi": "दक्षिण",  "significance_en": "Yama's zone — discipline, heavy structures",           "significance_hi": "यम का क्षेत्र — अनुशासन, भारी संरचनाएँ"},
    "left_leg":  {"direction": "W",  "direction_hi": "पश्चिम",  "significance_en": "Varuna's zone — water, emotions, evening energy",      "significance_hi": "वरुण का क्षेत्र — जल, भावनाएँ, संध्या ऊर्जा"},
    "feet":      {"direction": "SW", "direction_hi": "नैऋत्य", "significance_en": "Material anchor — heaviest zone, master bedroom",       "significance_hi": "भौतिक लंगर — सबसे भारी क्षेत्र, मुख्य शयनकक्ष"},
}
